
# Site Settings
title: Training by Serli
email: tanguy.desplebain@serli.com
description: Training by Serli . FORMATIONS & WORKSHOPS
baseurl: "/formations"
url: "http://Seikicegus.github.io"
github_username:  Seikicegus
encoding: utf-8
# Build Settings
sass:
  sass_dir: _sass
include: ['js']
kramdown:
  input: GFM
